name: Build Debian Package
on: [push]
jobs:
  package:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
      - uses: actions/upload-artifact@v4
        with:
          path: debian/artifacts/
          name: debian_package
